### ISSUE TITLE
sometimes deploying is not working - race conditions with health_checks ?

### ISSUE THREAD

**Issue by sielaq** [eBayClassifiedsGroup/marathon_deploy#4]
```
###########################################################################################################################################
I, [2015-07-03T15:56:47.655965 #29464]  INFO -- : Checking if any deployments are already running for application some-webapp
I, [2015-07-03T15:56:47.726509 #29464]  INFO -- : Starting deployment of some-webapp
/var/lib/gems/1.9.1/gems/marathon_deploy-0.1.3/lib/marathon_deploy/deployment.rb:157:in `health_checks_defined?': undefined method `[]' for nil:NilClass (NoMethodError)
    from /var/lib/gems/1.9.1/gems/marathon_deploy-0.1.3/lib/marathon_deploy/marathon_client.rb:69:in `deploy'
    from /var/lib/gems/1.9.1/gems/marathon_deploy-0.1.3/bin/marathon_deploy:130:in `block in <top (required)>'
    from /var/lib/gems/1.9.1/gems/marathon_deploy-0.1.3/bin/marathon_deploy:124:in `each'
    from /var/lib/gems/1.9.1/gems/marathon_deploy-0.1.3/bin/marathon_deploy:124:in `<top (required)>'
    from /usr/local/bin/marathon_deploy:23:in `load'
    from /usr/local/bin/marathon_deploy:23:in `<main>'
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

**Comment by joncolby** [comment]
fixed.
